import {
  Perfil,
  Programa,
  Sede,
  Horario,
  Grupo,
  Estudiante,
  AsistenciaDocente,
  AlertaEstudiante,
  Seguimiento,
  Publicacion,
  Auditoria,
  AsistenciaEstudiante,
  ActividadPedagogica
} from '../types';

export const INITIAL_PROGRAMAS: Programa[] = [
  {
    id: 'prog-1',
    codigo: 'EPJA',
    nombre: 'Educación de Personas Jóvenes y Adultas',
    descripcion: 'Formación humanística y técnica para jóvenes y adultos de la comunidad.',
    activo: true,
  },
  {
    id: 'prog-2',
    codigo: 'EDUPER',
    nombre: 'Educación Permanente',
    descripcion: 'Capacitación comunitaria no formal y talleres continuos.',
    activo: true,
  },
  {
    id: 'prog-3',
    codigo: 'CEE',
    nombre: 'Educación Especial',
    descripcion: 'Atención inclusiva a personas con necesidades educativas especiales.',
    activo: true,
  },
];

export const INITIAL_SEDES: Sede[] = [
  {
    id: 'sede-1',
    nombre: 'Sede Poroma',
    direccion: 'Centro Poblado de Poroma, Municipio de Poroma, Chuquisaca',
    latitud: -18.539416,
    longitud: -65.426389,
    radio_m: 180,
    activo: true,
  },
  {
    id: 'sede-2',
    nombre: 'Sede San Juan de Horcas',
    direccion: 'Comunidad San Juan de Horcas, Municipio de Poroma, Chuquisaca',
    latitud: -18.601234,
    longitud: -65.450123,
    radio_m: 180,
    activo: true,
  },
];

export const INITIAL_HORARIOS: Horario[] = [
  {
    id: 'hor-1',
    nombre: 'Poroma - Habitual (Noche)',
    sede_id: 'sede-1',
    hora_ingreso: '18:30',
    tolerancia_hasta: '18:40',
    hora_salida: '22:00',
    es_invierno: false,
    dias_semana: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
    sede_nombre: 'Sede Poroma',
    activo: true,
  },
  {
    id: 'hor-2',
    nombre: 'Poroma - Horario de Invierno',
    sede_id: 'sede-1',
    hora_ingreso: '18:30',
    tolerancia_hasta: '18:40',
    hora_salida: '21:30',
    es_invierno: true,
    dias_semana: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
    sede_nombre: 'Sede Poroma',
    activo: true,
  },
  {
    id: 'hor-3',
    nombre: 'San Juan de Horcas - Tarde/Noche',
    sede_id: 'sede-2',
    hora_ingreso: '16:30',
    tolerancia_hasta: '16:40',
    hora_salida: '20:30',
    es_invierno: false,
    dias_semana: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
    sede_nombre: 'Sede San Juan de Horcas',
    activo: true,
  },
];

export const MOCK_SUPERADMIN: Perfil = {
  id: 'usr-director',
  nombre_completo: 'Prof. Mario Gutiérrez Flores',
  ci: '4567891 Sucre',
  rda: '102938',
  especialidad: 'Gestión Educativa & EPJA',
  nivel: 'Directivo',
  categoria: '1ra Categoría',
  materias: ['Administración Institucional'],
  programa_id: 'prog-1',
  sede_id: 'sede-1',
  dias_laborales: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
  horario_id: 'hor-1',
  rol: 'superadmin',
  activo: true,
  puede_publicar: true,
  fecha_incorporacion: '2020-02-01',
  sede_nombre: 'Sede Poroma',
  programa_nombre: 'EPJA',
  horario_nombre: 'Poroma - Habitual (Noche)'
};

export const MOCK_DOCENTES: Perfil[] = [
  MOCK_SUPERADMIN,
  {
    id: 'usr-doc-1',
    nombre_completo: 'Lic. Elena Ramos Mamani',
    ci: '6789123',
    rda: '204958',
    especialidad: 'Humanidades & Ciencias Sociales',
    nivel: 'Secundario EPJA',
    categoria: '2da Categoría',
    materias: ['Lenguaje y Comunicación', 'Ciencias Sociales'],
    programa_id: 'prog-1',
    sede_id: 'sede-1',
    dias_laborales: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
    horario_id: 'hor-1',
    rol: 'docente',
    activo: true,
    puede_publicar: true,
    fecha_incorporacion: '2022-03-01',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EPJA',
    horario_nombre: 'Poroma - Habitual (Noche)'
  },
  {
    id: 'usr-doc-2',
    nombre_completo: 'Ing. Roberto Condori Quispe',
    ci: '7891234',
    rda: '305967',
    especialidad: 'Sistemas & Agropecuaria',
    nivel: 'Técnico Medio',
    categoria: '3ra Categoría',
    materias: ['Computación e Informática', 'Operación de Maquinaria'],
    programa_id: 'prog-1',
    sede_id: 'sede-2',
    dias_laborales: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes'],
    horario_id: 'hor-3',
    rol: 'docente',
    activo: true,
    puede_publicar: false,
    fecha_incorporacion: '2023-02-15',
    sede_nombre: 'Sede San Juan de Horcas',
    programa_nombre: 'EPJA',
    horario_nombre: 'San Juan de Horcas - Tarde/Noche'
  },
  {
    id: 'usr-doc-3',
    nombre_completo: 'Prof. Carmen Torrez Salazar',
    ci: '8912345',
    rda: '406978',
    especialidad: 'Educación Permanente & Artesanías',
    nivel: 'Técnico Básico',
    categoria: '4ta Categoría',
    materias: ['Corte y Confección', 'Pollería Tradicional'],
    programa_id: 'prog-2',
    sede_id: 'sede-1',
    dias_laborales: ['lunes', 'miércoles', 'viernes'],
    horario_id: 'hor-1',
    rol: 'docente',
    activo: true,
    puede_publicar: false,
    fecha_incorporacion: '2024-01-10',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EDUPER',
    horario_nombre: 'Poroma - Habitual (Noche)'
  }
];

export const INITIAL_GRUPOS: Grupo[] = [
  {
    id: 'grp-1',
    nombre: 'EPJA Nivel Secundario Avanzado - Poroma',
    sede_id: 'sede-1',
    programa_id: 'prog-1',
    carrera_especialidad: 'Humanidades / Agropecuaria',
    nivel: 'Avanzado',
    activo: true,
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EPJA'
  },
  {
    id: 'grp-2',
    nombre: 'Sistemas e Informática - S.J. Horcas',
    sede_id: 'sede-2',
    programa_id: 'prog-1',
    carrera_especialidad: 'Sistemas Informáticos',
    nivel: 'Técnico Medio',
    activo: true,
    sede_nombre: 'Sede San Juan de Horcas',
    programa_nombre: 'EPJA'
  },
  {
    id: 'grp-3',
    nombre: 'Corte y Confección Comunitaria - Poroma',
    sede_id: 'sede-1',
    programa_id: 'prog-2',
    carrera_especialidad: 'Textiles y Confección',
    nivel: 'Técnico Básico',
    activo: true,
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EDUPER'
  }
];

export const MOCK_ESTUDIANTES: Estudiante[] = [
  {
    id: 'est-1',
    codigo_interno: 'EST-2026-001',
    nombre_completo: 'Sonia Choque Villa',
    documento: '10293847',
    sexo: 'Femenino',
    fecha_inscripcion: '2026-07-27',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'ESA',
    sede_id: 'sede-1',
    carrera_especialidad: 'Humanidades / Agropecuaria',
    etapa: 'Secundaria Etapa Aplicada',
    nivel: 'Avanzado',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Asiste regularmente turno noche.',
    grupo_nombre: 'ESA Nivel Secundario Avanzado - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'ESA'
  },
  {
    id: 'est-2',
    codigo_interno: 'EST-2026-002',
    nombre_completo: 'Juan Carlos Mamani Perez',
    documento: '10928374',
    sexo: 'Masculino',
    fecha_inscripcion: '2026-07-27',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'ESA',
    sede_id: 'sede-1',
    carrera_especialidad: 'Humanidades / Agropecuaria',
    etapa: 'Secundaria Etapa Aplicada',
    nivel: 'Avanzado',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Trabaja en producción agrícola durante el día.',
    grupo_nombre: 'ESA Nivel Secundario Avanzado - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'ESA'
  },
  {
    id: 'est-3',
    codigo_interno: 'EST-2026-003',
    nombre_completo: 'María Inés Flores Torrez',
    documento: '11827364',
    sexo: 'Femenino',
    fecha_inscripcion: '2026-07-27',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'EPA',
    sede_id: 'sede-1',
    carrera_especialidad: 'Primaria de Adultos',
    etapa: 'Aprendizajes Elementales',
    nivel: 'Elemental',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Faltas recientes por temporada de cosecha.',
    grupo_nombre: 'EPA Elemental - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EPA'
  },
  {
    id: 'est-4',
    codigo_interno: 'EST-2026-004',
    nombre_completo: 'David Quispe Llanos',
    documento: '12938475',
    sexo: 'Masculino',
    fecha_inscripcion: '2026-07-28',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'ETA',
    sede_id: 'sede-2',
    carrera_especialidad: 'Sistemas Informáticos',
    etapa: 'Formación Técnica Tecnológica',
    nivel: 'Técnico Medio',
    grupo_id: 'grp-2',
    estado: 'activo',
    observacion: 'Sede San Juan de Horcas.',
    grupo_nombre: 'Sistemas e Informática - S.J. Horcas',
    sede_nombre: 'Sede San Juan de Horcas',
    programa_nombre: 'ETA'
  },
  {
    id: 'est-5',
    codigo_interno: 'EST-2026-005',
    nombre_completo: 'Martha Villegas Calani',
    documento: '13847566',
    sexo: 'Femenino',
    fecha_inscripcion: '2026-07-28',
    gestion: '2026',
    programa_id: 'prog-2',
    programa_codigo: 'EDUPER',
    sede_id: 'sede-1',
    carrera_especialidad: 'Textiles y Confección',
    etapa: 'Educación Permanente',
    nivel: 'Técnico Básico',
    grupo_id: 'grp-3',
    estado: 'activo',
    observacion: 'Taller de educación permanente.',
    grupo_nombre: 'Corte y Confección Comunitaria - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EDUPER'
  },
  {
    id: 'est-6',
    codigo_interno: 'EST-2026-006',
    nombre_completo: 'Roberto Mendoza Aliaga',
    documento: '14728394',
    sexo: 'Masculino',
    fecha_inscripcion: '2026-07-29',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'EPA',
    sede_id: 'sede-1',
    carrera_especialidad: 'Primaria de Adultos',
    etapa: 'Aprendizajes Elementales',
    nivel: 'Elemental',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Estudiante motivado en alfabetización.',
    grupo_nombre: 'EPA Elemental - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'EPA'
  },
  {
    id: 'est-7',
    codigo_interno: 'EST-2026-007',
    nombre_completo: 'Rosa María Yujra Cruz',
    documento: '15839201',
    sexo: 'Femenino',
    fecha_inscripcion: '2026-07-29',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'EPA',
    sede_id: 'sede-2',
    carrera_especialidad: 'Primaria de Adultos',
    etapa: 'Aprendizajes Avanzados',
    nivel: 'Avanzado',
    grupo_id: 'grp-2',
    estado: 'activo',
    observacion: 'Sede San Juan de Horcas.',
    grupo_nombre: 'EPA Avanzado - S.J. Horcas',
    sede_nombre: 'Sede San Juan de Horcas',
    programa_nombre: 'EPA'
  },
  {
    id: 'est-8',
    codigo_interno: 'EST-2026-008',
    nombre_completo: 'Carlos Eduardo Aruquipa',
    documento: '16928374',
    sexo: 'Masculino',
    fecha_inscripcion: '2026-07-30',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'ETA',
    sede_id: 'sede-1',
    carrera_especialidad: 'Agropecuaria',
    etapa: 'Formación Técnica Tecnológica',
    nivel: 'Técnico Auxiliar',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Módulo de riego agrícola.',
    grupo_nombre: 'Agropecuaria - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'ETA'
  },
  {
    id: 'est-9',
    codigo_interno: 'EST-2026-009',
    nombre_completo: 'Pedro Alcoba Gutierrez',
    documento: '17829304',
    sexo: 'Masculino',
    fecha_inscripcion: '2026-07-25',
    gestion: '2026',
    programa_id: 'prog-1',
    programa_codigo: 'EPA',
    sede_id: 'sede-2',
    carrera_especialidad: 'Primaria de Adultos',
    etapa: 'Aprendizajes Elementales',
    nivel: 'Elemental',
    grupo_id: 'grp-2',
    estado: 'retirado',
    fecha_retiro: '2026-07-29',
    observacion: 'Traslado de domicilio a Sucre.',
    grupo_nombre: 'EPA Elemental - S.J. Horcas',
    sede_nombre: 'Sede San Juan de Horcas',
    programa_nombre: 'EPA'
  },
  {
    id: 'est-10',
    codigo_interno: 'EST-2026-010',
    nombre_completo: 'Juana Laura Soliz',
    documento: '18930214',
    sexo: 'Femenino',
    fecha_inscripcion: '2026-07-30',
    gestion: '2026',
    programa_id: 'prog-3',
    programa_codigo: 'CEE',
    sede_id: 'sede-1',
    carrera_especialidad: 'Educación Especial Inclusiva',
    etapa: 'Educación Especial',
    nivel: 'Elemental',
    grupo_id: 'grp-1',
    estado: 'activo',
    observacion: 'Programa inclusivo adap. curricular.',
    grupo_nombre: 'Educación Inclusiva - Poroma',
    sede_nombre: 'Sede Poroma',
    programa_nombre: 'CEE'
  }
];

export const MOCK_ASISTENCIAS_DOCENTES: AsistenciaDocente[] = [
  {
    id: 'asis-1',
    docente_id: 'usr-doc-1',
    fecha_laboral: '2026-07-30',
    hora_ingreso_oficial: '2026-07-30T18:32:00-04:00',
    hora_salida_oficial: '2026-07-30T22:00:00-04:00',
    hora_ingreso_local: '2026-07-30T18:32:00-04:00',
    hora_salida_local: '2026-07-30T22:00:00-04:00',
    firma_ingreso: true,
    firma_salida: true,
    minutos_atraso: 0,
    minutos_salida_anticipada: 0,
    horas_trabajadas: 3.47,
    estado: 'puntual',
    origen_registro: 'en_linea',
    sync_key: 'sync-doc1-20260730',
    docente_nombre: 'Lic. Elena Ramos Mamani',
    sede_nombre: 'Sede Poroma',
    actividades_multigrado: [
      {
        id: 'act-1-1',
        area_nivel: 'ETA',
        subnivel: 'Técnico Básico',
        carrera: 'Gastronomía',
        actividad_pedagogica: 'Técnicas de corte de hortalizas y mis en place de cocina.'
      },
      {
        id: 'act-1-2',
        area_nivel: 'ETA',
        subnivel: 'Técnico Auxiliar',
        carrera: 'Gastronomía',
        actividad_pedagogica: 'Elaboración de salsas madre, fondos de cocina y emplatados.'
      }
    ]
  },
  {
    id: 'asis-2',
    docente_id: 'usr-doc-2',
    fecha_laboral: '2026-07-30',
    hora_ingreso_oficial: '2026-07-30T16:45:00-04:00',
    hora_salida_oficial: '2026-07-30T20:30:00-04:00',
    hora_ingreso_local: '2026-07-30T16:45:00-04:00',
    hora_salida_local: '2026-07-30T20:30:00-04:00',
    firma_ingreso: true,
    firma_salida: true,
    minutos_atraso: 15,
    minutos_salida_anticipada: 0,
    horas_trabajadas: 3.75,
    estado: 'atraso',
    origen_registro: 'sin_conexion',
    hora_sincronizacion: '2026-07-30T21:00:00-04:00',
    sync_key: 'sync-doc2-20260730',
    observacion: 'Sincronizado al volver señal en San Juan de Horcas',
    docente_nombre: 'Ing. Roberto Condori Quispe',
    sede_nombre: 'Sede San Juan de Horcas',
    actividades_multigrado: [
      {
        id: 'act-2-1',
        area_nivel: 'EPA',
        subnivel: 'Aprendizajes Elementales',
        actividad_pedagogica: 'Lectura comprensiva, caligrafía y resolución de problemas aritméticos.'
      },
      {
        id: 'act-2-2',
        area_nivel: 'EPA',
        subnivel: 'Aprendizajes Avanzados',
        actividad_pedagogica: 'Redacción de textos formales y cálculo de porcentajes.'
      }
    ]
  }
];

export const MOCK_ALERTAS: AlertaEstudiante[] = [
  {
    id: 'alt-1',
    estudiante_id: 'est-3',
    grupo_id: 'grp-1',
    docente_id: 'usr-doc-1',
    tipo: 'rojo_3_faltas',
    faltas_consecutivas: 3,
    estado: 'pendiente',
    created_at: '2026-07-29',
    estudiante_nombre: 'María Inés Flores Torrez',
    grupo_nombre: 'EPJA Nivel Secundario Avanzado - Poroma',
    docente_nombre: 'Lic. Elena Ramos Mamani'
  }
];

export const MOCK_SEGUIMIENTOS: Seguimiento[] = [
  {
    id: 'seg-1',
    alerta_id: 'alt-1',
    estudiante_id: 'est-3',
    docente_id: 'usr-doc-1',
    fecha: '2026-07-30',
    motivo: 'Inasistencia a 3 sesiones consecutivas del módulo de Lenguaje.',
    accion_realizada: 'llamada',
    resultado: 'Se contactó a la madre. La estudiante se encontraba ayudando en cosecha agrícola.',
    proxima_accion: 'Reincorporación confirmada para el lunes 3 de agosto.',
    observacion: 'Se acordó plan de nivelación con trabajos prácticos.',
    estado: 'pendiente',
    estudiante_nombre: 'María Inés Flores Torrez',
    docente_nombre: 'Lic. Elena Ramos Mamani'
  }
];

export const MOCK_PUBLICACIONES: Publicacion[] = [
  {
    id: 'pub-rm-001',
    titulo: 'Resolución Ministerial 001/2026 - Normas Generales de la Gestión Educativa',
    descripcion: 'Normativa oficial que regula la planificación, organización y evaluación en la Educación de Personas Jóvenes y Adultas (EPJA) y Educación Permanente.',
    categoria: 'rm_001_2026',
    fecha: '2026-07-27',
    destacado: true,
    archivo_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tipo_archivo: 'pdf',
    nombre_archivo: 'RM_001_2026_Bolivia_EPJA.pdf',
    contenido_texto: 'Resolución Ministerial No. 001/2026. Normas generales para la gestión educativa y administrativa del Subsistema de Educación Alternativa y Especial. Calendario escolar, inscripciones y carga horaria.',
    autor_nombre: 'Director General',
    archivado: false,
  },
  {
    id: 'pub-poa-2026',
    titulo: 'Plan Operativo Anual (POA 2026) - CEA Micaela Bastidas',
    descripcion: 'Documento presupuestario y plan de metas institucionales para las sedes Poroma y San Juan de Horcas.',
    categoria: 'poa',
    fecha: '2026-07-28',
    destacado: true,
    archivo_url: 'https://export.example.com/poa_2026_cea.xlsx',
    tipo_archivo: 'excel',
    nombre_archivo: 'POA_2026_CEA_Micaela_Bastidas.xlsx',
    contenido_texto: 'Plan Operativo Anual 2026. Objetivos estratégicos, infraestructura, presupuesto comunitario y seguimiento de metas.',
    autor_nombre: 'Dirección Institucional',
    archivado: false,
  },
  {
    id: 'pub-comunicado-1',
    titulo: 'Inicio del Periodo Operativo Segundo Semestre 2026',
    descripcion: 'Se informa a todo el personal docente el inicio de actividades académicas del 27 de julio al 14 de diciembre de 2026.',
    categoria: 'comunicados',
    fecha: '2026-07-27',
    destacado: false,
    tipo_archivo: 'ninguno',
    autor_nombre: 'Dirección CEA',
    archivado: false,
  }
];

export const MOCK_AUDITORIA: Auditoria[] = [
  {
    id: 'aud-1',
    usuario_nombre: 'Prof. Mario Gutiérrez Flores',
    accion: 'Modificación de horario de invierno',
    tabla_afectada: 'horarios',
    registro_afectado_id: 'hor-2',
    valor_anterior: { hora_salida: '22:00' },
    valor_nuevo: { hora_salida: '21:30' },
    motivo_correccion: 'Aplicación de instructivo de horario de invierno por bajas temperaturas.',
    created_at: '2026-07-28 10:15:00'
  }
];
